print("=== CYBER ARCHIVES - DATA RECOVERY SYSTEM ===\n")
file = open("ancient_fragment.txt", "r")
data = file.read()
print("Accessing Storage Vault: ancient_fragment.txt")
print("Connection established...\n")
print("RECOVERED DATA:")
print(data)
file.close()
